### PR TITLE
disable colour on salt docker runs

### PR DESCRIPTION
**Pull request by Azulinho**
As part of:
https://opgtransform.atlassian.net/browse/OPGOPS-1895

In order to issue the correct escape codes for highligthing ouput as per 1895, we need to scrap all the 'green output' produced by salt docker runs.

### CODE REVIEW

**Comment by tim-mcarthur-moj** [comment]
https://github.com/ministryofjustice/opg-cotton/blob/2d39c74e3408576f7e9efdab4fa9ac6fd13f8df7/cotton/salt/wrappers.py#L44 is where most of the salt calls get generated, so this change would be needed here too

**Comment by Azulinho** [comment]
yeap, but for now this change is only about the salt docker runs

**Comment by tim-mcarthur-moj** [comment]
ok. then just a version increment in setup.py for pip is needed

**Comment by Azulinho** [comment]
done, I didn't update CHANGE.LOG as it seems to be fairly out of date

**Comment by Azulinho** [comment]
thaaaaaaaaaaaaaaaaaaaaaaaaaaaaaannnkzzzzz

**Pull request merged**
